apiVersion: v1
data:
  customAlertRules.yaml: |-
    groups:
    - name: CustomAlerts
      rules:
        - alert: HostRunningOutOfMemory
          expr: node_memory_MemAvailable_bytes * 1000000 < 200
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: Host out of memory (instance {{ $labels.instance }})
            description: "Node memory is filling up (< 10% left)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/name: monitoring
  name: <YOURNAME>-alerts
  namespace: kube-devops