apiVersion: v1
data:
  extendedqueries.yaml: |-
  {{- $files := .Files }}
  {{- range $path, $_ :=  .Files.Glob  "extensions/*.yaml" }}
  {{- $.Files.Get $path | trim | nindent 4 -}}
  {{- end }}
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/name: monitoring.cactestreply
  name: {{ .Release.Name }}-extended-queries
  namespace: kube-devops
