apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name:  {{ .Release.Name }}-secret-provider
spec:
  provider: azure
  secretObjects:
  - secretName: {{ .Release.Name }}-secrets-store
    type: Opaque
    data:
      - objectName: {{.Values.keyvaultAccess.objectKey}}
        key: postgresql-exporter-user-pass
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{.Values.keyvaultAccess.managedIdentityClientId}}
    keyvaultName: {{.Values.keyvaultAccess.keyVaultName}}
    cloudName: ""
    objects: |
      array:
        - |
          objectName: {{.Values.keyvaultAccess.objectKey}}
          objectType: secret
          objectVersion: ""
    tenantId: {{.Values.keyvaultAccess.tenantId}}