apiVersion: v1
kind: Service
metadata:
  name:  {{ .Release.Name }}-service
  annotations:
    prometheus.io/scrape: "true"
  labels:
    exporters: postgresql
spec:
  ports:
  - port: 80
    targetPort: 9187
    protocol: TCP
  selector:
    exporters: postgresql
    serviceSelector:  {{ .Release.Name }}-servicetarget