apiVersion: v1
data:
  postgresql_exporter.yaml: |-
    - targets:
      - exporter-postgresql.kube-devops.svc.cluster.local
      labels:
        app: postgresql
        #Actually /metrics is default, used just as an example
        __metrics_path__: /metrics
  kafka_exporter.yaml: |-
    - targets:
      - <yourKafkaHost>
      labels:
        app: kafka
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/name: monitoring
  name: prometheus-custom-exporters
  namespace: kube-devops
